---
- name: install required packages for firewalld
  package:
    name: '{{ item }}'
    state: present
  with_items:
    - firewalld
#  vars:
#    ansible_python_interpreter: /usr/bin/python
       
- name: install firewalld
  yum: name=firewalld state=present

- name: firewalld service state
  service: name=firewalld state=started enabled=yes

- name: OPTIONAL Install or upgrade the net-tools package
  yum: name=net-tools state=latest
  
- name: Add ports to firewall
  ansible.posix.firewalld:
    port: "22/tcp"
    state: enabled
    immediate: true
    permanent: true



- name: firewalld rules
#  ansible.posix.firewalld:
  firewalld:
    permanent: yes
    immediate: yes
    service: "{{ item }}"
    state: enabled
  with_items:
   - ssh
   - http