---
- name: install required packages for firewalld
  package:
    name: '{{ item }}'
    state: present
  with_items:
    - firewalld
       
- name: install firewalld
  yum: name=firewalld state=present
  
- name: firewalld service state
  service: name=firewalld state=started enabled=yes

- name: firewalld rules
  firewalld:
    permanent: yes
    immediate: yes
    service: "{{ item }}"
    state: enabled
  with_items:
   - ssh
   - http
 
- name: install fail2ban
  yum: name=fail2ban state=present

- name: install fail2ban-firewalld
  yum: name=fail2ban-firewalld state=present

- name: fail2ban configuration file /etc/fail2ban/jail.local
  ansible.builtin.copy:
    src: files/jail.local
    dest: /etc/fail2ban/jail.local
    mode: '0655'   

- name: fail2ban configuration file /etc/fail2ban/jail.d/00-firewalld.local
  ansible.builtin.copy:
    src: files/00-firewalld.local
    dest: /etc/fail2ban/jail.d/00-firewalld.local
    mode: '0655'

- name: fail2ban configuration file /etc/fail2ban/jail.d/sshd.local
  ansible.builtin.copy:
    src: files/sshd.local
    dest: /etc/fail2ban/jail.d/sshd.local
    mode: '0655'

- name: fail2ban service state
  service: name=fail2ban state=restarted enabled=yes