---
- name: install required packages for firewalld
  package:
    name: '{{ item }}'
    state: present
  with_items:
    - firewalld
  vars:
    ansible_python_interpreter: /usr/bin/python3
       
- name: install firewalld
  yum: name=firewalld state=present

- name: firewalld service state
  service: name=firewalld state=started enabled=yes

- name: firewalld rules
  firewalld:
    permanent: yes
    immediate: yes
    service: "{{ item }}"
    state: enabled
  with_items:
   - ssh
   - http
 
   